import { extractYouTubeId } from "./types.js";

const DEFAULT_USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

interface CaptionTrack {
  baseUrl: string;
  url?: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string };
}

interface TranscriptSegment {
  text: string;
  offset: number;
  duration: number;
}

function formatTimestamp(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) {
    return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  }
  return `${m}:${String(s).padStart(2, "0")}`;
}

async function getCaptionTracks(videoId: string): Promise<CaptionTrack[]> {
  const watchUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const watchRes = await fetch(watchUrl, {
    headers: { "User-Agent": DEFAULT_USER_AGENT, "Accept-Language": "en" },
  });
  const watchHtml = await watchRes.text();

  const apiKeyMatch =
    watchHtml.match(/"INNERTUBE_API_KEY":"([^"]+)"/) ||
    watchHtml.match(/INNERTUBE_API_KEY\\":\\"([^\\"]+)\\"/);
  if (!apiKeyMatch) {
    throw new Error(`Could not find API key for video ${videoId}`);
  }

  const playerRes = await fetch(
    `https://www.youtube.com/youtubei/v1/player?key=${apiKeyMatch[1]}`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent": DEFAULT_USER_AGENT,
      },
      body: JSON.stringify({
        context: {
          client: {
            clientName: "ANDROID",
            clientVersion: "20.10.38",
          },
        },
        videoId,
      }),
    }
  );

  const playerJson = await playerRes.json();
  const tracklist =
    playerJson?.captions?.playerCaptionsTracklistRenderer ??
    playerJson?.playerCaptionsTracklistRenderer;

  if (!tracklist?.captionTracks?.length) {
    throw new Error(`No captions available for video ${videoId}`);
  }

  return tracklist.captionTracks;
}

function selectBestTrack(tracks: CaptionTrack[]): CaptionTrack {
  const enTracks = tracks.filter((t) => t.languageCode === "en");
  if (enTracks.length > 0) {
    const curated = enTracks.find((t) => t.kind !== "asr");
    return curated || enTracks[0];
  }
  const curated = tracks.find((t) => t.kind !== "asr");
  return curated || tracks[0];
}

async function downloadTranscriptXml(
  track: CaptionTrack
): Promise<TranscriptSegment[]> {
  let url = track.baseUrl || track.url;
  if (!url) throw new Error("Caption track has no URL");
  url = url.replace(/&fmt=[^&]+$/, "");

  const res = await fetch(url, {
    headers: { "User-Agent": DEFAULT_USER_AGENT, "Accept-Language": "en" },
  });
  const xml = await res.text();

  const segments: TranscriptSegment[] = [];
  const regex =
    /<text\s+start="([\d.]+)"\s+dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
  let match;
  while ((match = regex.exec(xml)) !== null) {
    const text = match[3]
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/<[^>]+>/g, "")
      .trim();
    if (text) {
      segments.push({
        offset: parseFloat(match[1]),
        duration: parseFloat(match[2]),
        text,
      });
    }
  }

  return segments;
}

export interface YouTubeResult {
  title: string;
  videoId: string;
  thumbnail: string;
  captions: "curated" | "auto-generated";
  transcript: string;
}

/**
 * Downloads a YouTube transcript with timestamps.
 * Returns clean content (no frontmatter) for the agent to assemble.
 */
export async function downloadYouTubeTranscript(
  url: string,
  title: string
): Promise<YouTubeResult> {
  const videoId = extractYouTubeId(url);
  if (!videoId) throw new Error(`Could not extract video ID from: ${url}`);

  const tracks = await getCaptionTracks(videoId);
  const track = selectBestTrack(tracks);
  const isAutoGenerated = track.kind === "asr";

  console.log(
    `  captions: ${isAutoGenerated ? "auto-generated" : "curated"} (${track.languageCode})`
  );

  const segments = await downloadTranscriptXml(track);
  const lines = segments.map(
    (seg) => `[${formatTimestamp(seg.offset)}] ${seg.text}`
  );

  return {
    title,
    videoId,
    thumbnail: `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
    captions: isAutoGenerated ? "auto-generated" : "curated",
    transcript: lines.join("\n"),
  };
}

/**
 * Fetch YouTube video title from the page HTML.
 */
export async function fetchYouTubeTitle(url: string): Promise<string> {
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": DEFAULT_USER_AGENT },
    });
    const html = await res.text();
    const match = html.match(/<title>([^<]+)<\/title>/);
    if (match) {
      return match[1].replace(/ - YouTube$/, "").trim();
    }
  } catch {}
  return "Untitled Video";
}
